apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-webapp
spec:
  hosts:
  - "example.com"
  gateways:
  - app-gateway
  http:
  - route:
    - destination:
        host: webapp1-svc
        port:
          number: 80
