apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-path-webapp1
spec:
  hosts:
  - "abcd.com"
  gateways:
  - gateway # this is referring to the app-gateway created inside the istio-system namespace
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: webapp2-svc
        port:
          number: 80
