apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-path-webapp1
spec:
  hosts:
  - "abcd.com"
  gateways:
  - path-gateway # this is refering the app-gateway created inside istio-system namespace
  http:
  - match:
    - uri:
        prefix: "/webapp"
    route:
    - destination:
        host: webapp2-svc
        port:
          number: 80
